build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install -r requirements_dev.txt"
  - "%PYTHON%/Scripts/pip.exe install -r python-coveralls"
  - "%PYTHON%/Scripts/pip.exe install -r coveralls"
  - "mkdir tests/temp"

test_script:
  - "%PYTHON%/Scripts/nosetests"
